@node    Overview, Invoking Yafc, top, top
@chapter Overview

This manual documents @sc{Yafc}. @sc{Yafc} is quite a powerful ftp client.
It is a console interface to the ftp protocol. If you're looking for a nice
GUI client, Yafc is not for you. If you, however, use ftp often and want a
fast, powerful, friendly client Yafc is here for you...

Some of the features are recursive get/put/ls/rm, nohup transfers, colored ls,
cached directory listings, autologin and bookmarks, powerful aliases and
extensive tab completion.

To my knowledge, Yafc is the only ftp client that has colored ls.

This manual is incomplete, and possibly out of date. If you would like
to improve this manual, please send a message to @email{mhe@@stacken.kth.se}.

@menu
* Bugs::                Reporting bugs and requests
* Obtaining Yafc::      Where to get Yafc
* Motivation::          Why Yafc was written
@end menu

@c -----------------------------------------------------
@node Bugs, Obtaining Yafc, , Overview
@subsection Bugs

Please report bugs to @email{mhe@@stacken.kth.se}.
Before reporting a bug, please verify you're using the latest version
(check the ftp site.) You can get the version number of your copy of yafc
with the command @code{yafc --version}.

When reporting bugs, please include information on
what machine and operating system, including versions, you are running, an
example for me to reproduce (use the @code{--trace} option) and a patch if you have one.

@c -----------------------------------------------------
@node    Obtaining Yafc, Motivation, Bugs, Overview
@subsection Obtaining Yafc

@table @asis

@item Yafc homepage
@uref{http://www.stacken.kth.se/~mhe/yafc/}

@item Yafc official FTP site
@uref{ftp://mayer.physto.se/pub/yafc/}

@end table

@c -----------------------------------------------------
@node    Motivation, , Obtaining Yafc, Overview
@subsection Motivation

Yafc was created because I needed a good ftp client.
The standard BSD ftp client lacks tab completion, something I've
become used to and can't live without. Of course, both Lftp and NcFtp
has tab completion, but not good enough for me :-). Also, I needed
a client that understood Kerberos4 authentication, because that's the
security system used a KTH (The Royal Institute of Technology in Sweden, where
I am studying.) 

But perhaps most important, I needed a fun project to work on :-)
