@node Invoking Yafc, The shell, Overview, Top
@chapter Invoking Yafc
@cindex command line options

Usage:
@example
yafc [options] [proto://][@var{user}[:@var{password}]@@]@var{hostname}[:@var{port}][/@var{directory}]
@end example

The 'proto' keyword can be either 'ftp' for ordinary FTP protocol, or
'ssh' for SSH2 protocol (sftp).

Options:

@table @samp

@item -a
@itemx --anon
Try an anonymous login, ie login as "anonymous" with your email address as
password. Your email address is first looked for in the config file
(@ref{Keywords}), then in the $EMAIL environment variable. If it's not
found, a guess is made from your user- and hostname.

@item -d
@itemx --debug
Print all messages sent to/from server.

@item -D
@itemx --dump-rc
Prints the default configuration file to standard output.

@item -m
@itemx --mechanism=@var{MECH}
Try security mechanism MECH when logging in to the host specified on the
command line. This will override any 'mech' options in @file{yafcrc} or
@file{bookmarks}. MECH is a colon-separated string,
supported values are "krb4", "krb5" and "none". The mechanisms are tried in
the order specified.

@item -n
@itemx --norc
Do not read the users configuration file. This will cause yafc to use its
default settings.

@item -p
@itemx --noproxy
Do not connect via the proxy. This should be used if connecting to a host on
the local network.

@item -q
@itemx --quiet
Do not print the welcome message with copyright information when starting Yafc.

@item -r @var{FILE}
@itemx --rcfile=@var{FILE}
Read another configuration file.

@item -t @var{FILE}
@itemx --trace[=@var{FILE}]
Enable creation of trace file. Trace files are mainly for debugging and
includes every response and command Yafc receives/sends. If FILE is specified,
use that file instead of the default trace file
(@file{~/.yafc/trace/trace.pid}, where pid is the process id number of Yafc.)
Trace files can grow quite large and can safely be deleted.

@item -u
@itemx --noauto
Do not login automagically to the host specified on the command line. You can
still use bookmark aliases, though.

@item -U
@itemx --noalias
As ---noauto, but bookmark aliases is disabled.

@item -v
@itemx --verbose
Print all responses received (without response code.)

@item -w
@itemx --wait=@var{TIME}
Use a different time to wait between connection attempts, in seconds.
This overrides the value set by @code{connect_wait_time} in the configuration
file.

@item -W
@itemx --workdir=@var{DIR}
Use a different working directory for configuration files and
temporary files. Default is @file{~/.yafc}.

@item -V
@itemx --version
Print version information on stdout and exit successfully.

@item -h
@itemx --help
Print a short help description on stdout and exit successfully.

@end table
