\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename yafc.info
@settitle Yafc
@dircategory Internet
@setchapternewpage odd
@c %**end of header

@include version.texi

@ifinfo
@format
START-INFO-DIR-ENTRY
* Yafc: (yafc).  Yet Another FTP Client
END-INFO-DIR-ENTRY
@end format
This file documents Yafc version @value{VERSION}

Copyright @copyright{} 1999-2000 Martin Hedenfalk

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the copyright holder.
@end ifinfo

@c  This title page illustrates only one of the
@c  two methods of forming a title page.

@titlepage
@title Yafc -- Yet Another FTP Client
@subtitle version @value{VERSION}, @value{UPDATED}
@author Martin Hedenfalk

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1999-2000 Martin Hedenfalk

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the copyright holder.
@end titlepage

@node Top, Overview, , (dir)

@ifinfo
This document describes @sc{Yafc}, an interactive interface to the FTP protocol.
This document applies to version @value{VERSION}.
@end ifinfo

@menu
* Overview::                    Introduction to Yafc
* Invoking Yafc::               How to start Yafc
* The shell::                   
* Configuration::               How to configure Yafc
* Bookmarks::                   
* Kerberos::                    How Yafc uses Kerberos
@end menu

@c *****************************************************
@include yafc_intro.texi
@c *****************************************************
@include yafc_invoke.texi
@c *****************************************************
@include yafc_shell.texi
@c *****************************************************
@include yafc_config.texi
@c *****************************************************
@include yafc_bookmark.texi
@c *****************************************************
@node Kerberos, , Bookmarks, top
@chapter Kerberos

If Yafc is compiled with Kerberos, it tries to authenticate using Kerberos 5
without sending the password in cleartext. For anonymous logins, Kerberos
is never used. The default protection level for data connections is
clear, ie no encryption on transfers. Use the command @code{prot}
(@ref{prot}), to change the data protection level. Valid arguments are
@code{clear}, @code{safe}, and @code{private}. Note that confidential
protection is not supported in Kerberos 4. You can use the @samp{prot} keyword
(@pxref{Bookmark keywords}) in the bookmarks file to automagically set the
protection level for a specific host.

@c *****************************************************
@contents

@bye
