@node Yafc commands, Nohup transfers, , The shell
@section Yafc commands

All commands follow the usual GNU command line syntax,
with long options starting with two dashes (@samp{--}).

Most commands have an option @samp{--help} that shows a
short syntax description.

@menu
* !::                           execute shell command
* afslog::                      
* alias::                       create an alias
* bookmark::                    create a bookmark
* cache::                       control directory cache
* cat::                         view a text file
* cd::                          change working directory
* cdup::                        change to parent directory
* chmod::                       change access mode (permissions) of files
* close::                       close connection
* copyright::                   show copyright notice
* filesize::                    print filesize in bytes
* filetime::                    print file modification time
* get::                         get files
* help::                        
* idle::                        modify idle time
* kauth::                       authenticate to Kerberos
* kdestroy::                    destroy Kerberos tickets
* klist::                       list Kerberos tickets
* krbtkfile::                   specify Kerberos ticket file
* lcd::                         change local working directory
* list::                        show raw directory listing
* lpwd::                        print local working directory
* ls::                          show directory listing
* ltag::                        tag local files
* luntag::                      remove files from local taglist
* mkdir::                       create directory
* mv::                          move files
* nlist::                       show filename list
* nop::                         do nothing
* open::                        open a connection
* prot::                        change Kerberos data protection level
* put::                         put files
* pwd::                         print working directory
* quit::                        quit Yafc
* quote::                       send arbitrary FTP command
* rhelp::                       remote help
* rm::                          remove files
* rmdir::                       remove empty directory
* rstatus::                     show status
* set::                         show and set variables
* shell::                       execute local shell
* site::                        issue a site specific FTP command
* source::                      read a configuration file
* status::                      show local status
* switch::                      switch between open connections
* system::                      show type of system
* tag::                         tag files
* unalias::                     remove an alias
* untag::                       remove files from taglist
* url::                         print the current FTP url
* user::                        send new user information
* version::                     show Yafc version
* warranty::                    show lack of warranty
@end menu

@c -----------------------------------------------------
@node !
@subsection @code{!}
This is a synonym for the shell (@ref{shell}) command.

@c -----------------------------------------------------
@node afslog
@subsection @code{afslog}
Documentation missing...

@c -----------------------------------------------------
@node alias
@subsection @code{alias}
Define an alias.

@c -----------------------------------------------------
@node bookmark
@subsection @code{bookmark}

@c -----------------------------------------------------
@node cache
@subsection @code{cache}

Control the directory cache.

Usage:
@example
cache [options] [directory ...]
@end example

Options:

@table @samp

@item  -c
@itemx --clear
Clear the whole directory cache.

@item  -l
@itemx --list
List the contents of the directory cache.

@item  -t
@itemx --touch
Remove the specified directories from the cache. If no directories are
given as arguments, the current directory is removed from the cache.

@item  -h
@itemx --help
Show a short help description.

@end table

@c -----------------------------------------------------
@node cat
@subsection @code{cat}
Print file(s) on standard output. All files are transferred in binary mode, so
it is safe to do a @code{cat foo.tar.gz > bar.tar.gz}.

Usage:
@example
cat [options] file ...
@end example

Options:

@table @samp
@item -h, --help
Show a short help description
@end table

@c -----------------------------------------------------
@node cd
@subsection @code{cd}
Change remote working directory.

Usage:
@example
cd [directory]
@end example

If no argument is given, @code{cd} changes to the home directory. The home
directory is the current directory when logged in.

If the argument is '-', @code{cd} changes to the previous working directory.

@c -----------------------------------------------------
@node cdup
@subsection @code{cdup}
Changes to parent directory. On UN*X systems, this is the same as @code{cd ..}.

@c -----------------------------------------------------
@node chmod
@subsection @code{chmod}
Change the permission mode of remote files.

Usage:
@example
chmod mode file ...
@end example

Mode must be given in octal representation (for example: 0644 is -rw-r--r--).

@c -----------------------------------------------------
@node close
@subsection @code{close}
Close active connection.

@c -----------------------------------------------------
@node copyright
@subsection @code{copyright}
Show copyright.

@c -----------------------------------------------------
@node filesize
@subsection @code{filesize}

@c -----------------------------------------------------
@node filetime
@subsection @code{filetime}

@c -----------------------------------------------------
@node get
@subsection @code{get}

Transfer files from remote server to local computer.

Usage:
@example
get [options] file ...
@end example

Options:

@table @samp

@item  -a
@itemx --append
Append if destination exists.

@item -c @var{PERM}
@itemx --chmod=@var{PERM}
Change mode of transferred files to PERM.

@item --chgrp=@var{GROUP}
change group of transferred files to GROUP.
You need to be a member of GROUP.

@item -d
@itemx --no-dereference
Copy symbolic links as symbolic links.

@item -D
@itemx --delete-after
Delete remote file after successful transfer.

@item --dir-mask=@var{GLOB}
Enter only directories matching GLOB pattern.

@item --dir-rx-mask=@var{REGEXP}
Enter only directorues matching REGEXP pattern.

@item -f
@itemx --force
Overwrite existing destinations, never prompt.

@item -H
@itemx --nohup
Transfer files in background (nohup mode), quits yafc.

@item -i
@itemx --interactive
Prompt before each transfer.

@item -L @var{FILE}
@itemx --logfile=@var{FILE}
Use @var{FILE} as logfile instead of @file{~/.yafc/nohup/nohup.<pid>}.

@item -m @var{GLOB}
@itemx --mask=@var{GLOB}
Only get file matching GLOB pattern.

@item -M @var{REGEXP}
@itemx --rx-mask=@var{REGEXP}
Only get files matching REGEXP pattern.

@item -n
@itemx --newer
Only get file if remote is newer than local file.

@item -o @var{DEST}
@itemx --output=@var{DEST}
Store in local directory @var{DEST}.

@item -p
@itemx --preserve
Try to preserve file attributes and timestamps.

@item -P
@itemx --parents
Append source path to destination.

@item -q
@itemx --quiet
Overrides @samp{--verbose}.

@item -r
@itemx --recursive
Get directories recursively.

@item -R
@itemx --resume
Resume broken download (restart at EOF).

@item -s
@itemx --skip-existing
Always skip existing files.

@item -t
@itemx --tagged
Transfer tagged files.

@item --type=@var{TYPE}
Specify transfer type, 'ascii' or 'binary'.

@item -u
@itemx --unique
Always store as unique local file.

@item -v
@itemx --verbose
Explain what is being done.

@item --help
Show a short syntax description.

@end table

@c -----------------------------------------------------
@node help
@subsection @code{help}

@c -----------------------------------------------------
@node idle
@subsection @code{idle}
Show or set the idle timeout.

@c -----------------------------------------------------
@node kauth
@subsection @code{kauth}
Authenticate to Kerberos.

@c -----------------------------------------------------
@node kdestroy
@subsection @code{kdestroy}
Destroy Kerberos tickets.

@c -----------------------------------------------------
@node klist
@subsection @code{klist}
Show Kerberos tickets.

@c -----------------------------------------------------
@node krbtkfile
@subsection @code{krbtkfile}
Set file used for Kerberos tickets.

@c -----------------------------------------------------
@node lcd
@subsection @code{lcd}
Change local working directory.

@c -----------------------------------------------------
@node list
@subsection @code{list}
List files.

@c -----------------------------------------------------
@node lpwd
@subsection @code{lpwd}
Print local working directory.

@c -----------------------------------------------------
@node ls
@subsection @code{ls}
List files.

Usage:
@example
ls [options] [files ...]
@end example

Options:

@table @samp

@item -a
@itemx --all
Do not hide entries starting with '.'.

@item -A
@item --almost-all
As @samp{--all}, but do not list . and ..

@item -B
@itemx --ignore-backups
Do not list implied entries ending with ~.

@item -C
List entries by columns.

@item --color[=@var{WHEN}]
Control whether color is used to distinguish file types. @var{WHEN} may be
either @var{never}, @var{always} or @var{auto}. If @var{WHEN} is not given,
default is @var{always}. If the argument is @var{auto}, colors will be used
only if output is bound to a tty.

@item -d
@itemx --directory
List directory entries instead of contents.

@item --dirs-first
Show directories first (last with @samp{--reverse}).

@item -F
@itemx --classify
Append a character for typing each entry.

@item -g
Ignored.

@item -G
@itemx --no-group
Inhibit display of group information.

@item -h
@item --human-readable
Print sizes in human readable format (e.g. 1K, 234M, 2G)

@item -l
Use a long listing format.

@item -N
@itemx --literal
Print raw entry names (don't treat control characters specially)

@item -o
Use a long listing format without group info. Same as @samp{-lG}.

@item -r
@itemx --reverse
Reverse order while sorting.

@item -R
@itemx --recursive
List subdirectories recursively.

@item -S
Sort by file size

@item -t
Sort by modification time.

@item -U
Do not sort; list entries in directory order.

@item -x
List entries by lines instead of by columns.

@item -X
Sort alphabetically by entry extension.

@item -1
List one file per line.

@item --help
Show a short syntax description.

@end table

@c -----------------------------------------------------
@node ltag
@subsection @code{ltag}
Tag local files.

@c -----------------------------------------------------
@node luntag
@subsection @code{luntag}
Untag local files.

@c -----------------------------------------------------
@node mkdir
@subsection @code{mkdir}
Creates a remote directory (requires proper permissions.)

Usage:
@example
mkdir directory
@end example

@c -----------------------------------------------------
@node mv
@subsection @code{mv}

@c -----------------------------------------------------
@node nlist
@subsection @code{nlist}

@c -----------------------------------------------------
@node nop
@subsection @code{nop}

@c -----------------------------------------------------
@node open
@subsection @code{open}

Opens a new connection to an FTP server.

Usage:  open [options] [ftp://][user[:password]@@]hostname[:port][/directory] ...

Options:

@table @samp

@item -a
@itemx --anon
Try to login anonymously.

@item -u
@itemx --noauto
Disable autologin.

@item -U
@itemx --noalias
Disable bookmark alias lookup and abbreviation.

@item -m @var{MECH}
@itemx --mechanism @var{MECH}
Try security mechanism @var{MECH} when logging in. This will override any
'mech' options in @file{yafcrc} or @file{bookmarks}. @var{MECH} is a
colon-separated string, supported values are "krb4", "krb5" and "none". The
mechanisms are tried in the order specified.

@item --help
Show a short syntax description.

@end table

@c -----------------------------------------------------
@node prot
@subsection @code{prot}

Changes the data protection level for data transfers. The
protection level defines how data transfers are handled
by Kerberos. The control connection (where commands are
sent and received) are always private.

Usage: @code{prot <protlevel>}

Valid protection levels are:

@table @code

@item clear
no data protection

@item safe
integrity check

@item private
all data encrypted and integrity checked

@end table

@c -----------------------------------------------------
@node put
@subsection @code{put}

@c -----------------------------------------------------
@node pwd
@subsection @code{pwd}

Prints the current remote working directory.

Usage: @code{pwd}

@c -----------------------------------------------------
@node quit
@subsection @code{quit}

@c -----------------------------------------------------
@node quote
@subsection @code{quote}

@c -----------------------------------------------------
@node rhelp
@subsection @code{rhelp}

@c -----------------------------------------------------
@node rm
@subsection @code{rm}

Remove files on remote server.

Usage: @code{rm [options] file...}

Options:

@table @samp

@item -f
@itemx --force
never prompt

@item -i
@itemx --interactive
prompt before any removal

@item -r
@itemx --recursive
remove the contents of directories recursively. CAREFUL!

@item -t
@itemx --tagged
remove tagged files

@item -v
@itemx --verbose
explain what is being done

@item --help
display help

@end table

@c -----------------------------------------------------
@node rmdir
@subsection @code{rmdir}

@c -----------------------------------------------------
@node rstatus
@subsection @code{rstatus}

@c -----------------------------------------------------
@node set
@subsection @code{set}

@c -----------------------------------------------------
@node shell
@subsection @code{shell}

@c -----------------------------------------------------
@node site
@subsection @code{size}

@c -----------------------------------------------------
@node source
@subsection @code{source}

@c -----------------------------------------------------
@node status
@subsection @code{status}

@c -----------------------------------------------------
@node switch
@subsection @code{switch}

@c -----------------------------------------------------
@node system
@subsection @code{system}

@c -----------------------------------------------------
@node tag
@subsection @code{tag}

@c -----------------------------------------------------
@node unalias
@subsection @code{unalias}

@c -----------------------------------------------------
@node untag
@subsection @code{untag}

@c -----------------------------------------------------
@node url
@subsection @code{url}

@c -----------------------------------------------------
@node user
@subsection @code{user}

@c -----------------------------------------------------
@node version
@subsection @code{version}

@c -----------------------------------------------------
@node warranty
@subsection @code{warranty}
